name: afrobambacar.github.io
description: Front end web music developer
meta_description: "A, Front end web music developer"
timezone: Asia/Seoul

aboutPage: false

# markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate, jekyll-gist]
paginate: 20
baseurl: /
domain_name: 'http://afrobambacar.github.io'
google_analytics: 'UA-51189334-1'

disqus: true
disqus_shortname: 'afr5'

# Details for the RSS feed generator
url:            'http://afrobambacar.github.io'
author:         'Jaecheol Lee'
authorTwitter:  'afr5'

permalink:       /:year/:month/:title.html

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
